export const topics = ['College admissions', 'Math & statistics', 'Science', 'Writing & English', 'Technology', 'Career exploration', 'Social studies', 'Study skills', 'Business & finance', 'Creative arts']
export const sampleMentors = [
  {id:'sample-1',full_name:'Jordan Ellis',major:'Government',year:'Junior',bio:'I remember how confusing the path to college could feel. I love talking about finding your voice, planning for applications, and exploring public service.',experience:'Student government · Policy research internship',goals:'Make public service more accessible',topics:['College admissions','Social studies','Writing & English'],skills:'Essay feedback, public speaking, research',availability:'Mon 4–6 PM · Thu 5–7 PM',status:'approved',avatar_url:'',accent:'peach'},
  {id:'sample-2',full_name:'Priya Shah',major:'Computer Science',year:'Senior',bio:'Technology belongs to everyone. Let’s talk about your first coding project, how to get into STEM, or how to build confidence in math.',experience:'Software engineering internship · Coding club mentor',goals:'Create inclusive technology for students',topics:['Technology','Math & statistics','Career exploration'],skills:'Python, algebra, web development',availability:'Tue 3–5 PM · Sat mornings',status:'approved',avatar_url:'',accent:'sage'},
  {id:'sample-3',full_name:'Marcus Reed',major:'Biology',year:'Sophomore',bio:'I’m excited to make science feel less intimidating. Ask me about classes, study strategies, research opportunities, or what college is like.',experience:'Undergraduate research assistant · STEM outreach',goals:'Explore medicine and community health',topics:['Science','Study skills','College admissions'],skills:'Biology, chemistry, study planning',availability:'Wed 4–6 PM',status:'approved',avatar_url:'',accent:'lavender'},
  {id:'sample-4',full_name:'Sofia Nguyen',major:'Business',year:'Junior',bio:'There isn’t only one way to build a career. I’m here for résumé questions, interview prep, first-job advice, and big-picture life questions.',experience:'Marketing internship · Campus career ambassador',goals:'Help more students discover pathways into business',topics:['Career exploration','Business & finance','College admissions'],skills:'Résumés, interviews, presentations',availability:'Fri 2–5 PM',status:'approved',avatar_url:'',accent:'sky'},
  {id:'sample-5',full_name:'Elliot Brooks',major:'English',year:'Senior',bio:'Stories are how we discover what matters to us. Bring your essay idea, a class assignment, or questions about the liberal arts.',experience:'Writing center peer tutor · Literary magazine editor',goals:'Teach writing and creative expression',topics:['Writing & English','Creative arts','Study skills'],skills:'Creative writing, essay revision, reading',availability:'Mon 3–5 PM',status:'approved',avatar_url:'',accent:'yellow'},
  {id:'sample-6',full_name:'Amara Johnson',major:'Mechanical Engineering',year:'Junior',bio:'Curiosity is the best starting point. I can share how I prepared for engineering, handled tricky classes, and found campus opportunities.',experience:'Robotics design team · Engineering internship',goals:'Support the next generation of engineers',topics:['Math & statistics','Science','Technology'],skills:'Physics, calculus, design projects',availability:'Thu 4–6 PM',status:'approved',avatar_url:'',accent:'rose'}
]
export const defaultSettings = {hero_title:'Your future has a cheering section.', hero_subtitle:'Real questions. Real guidance. Real people in your corner. Find a college student mentor who remembers what it’s like to be right where you are.',mission:'We believe guidance should never depend on your ZIP code or who you happen to know. Hook’Em Helpers helps young students discover approachable college volunteers ready to share what they’ve learned.',announcement:''}
export const makeInitials = name => String(name||'?').split(/\s+/).filter(Boolean).slice(0,2).map(s=>s[0]?.toUpperCase()).join('') || '?'
export const friendlyError = err => err?.message || 'Something went wrong. Please try again.'
